function h(){return document.getElementById("isa-boot-title")?.textContent?.trim()||document.querySelector('meta[name="application-name"]')?.content?.trim()||document.title?.split("\u2014")[0]?.trim()||"IS-Swagger"}function f(){return document.querySelector('meta[name="app-icon"]')?.content?.trim()||"mdi:file-code-outline"}function _(a,{headline:l,ns:e="ISS"}={}){const n=globalThis.React,r=globalThis.ReactDOM?.createRoot,s=globalThis.ISAFront?.Layout?.AppShell,d=globalThis.MaterialUI;if(!n?.createElement||!r||!s||!d?.Box)return!1;const{Box:p,Typography:m,Alert:u,Button:i}=d,c=h(),o=f(),t=document.getElementById("root");return t?(r(t).render(n.createElement(s,{ns:e,title:c,icon:o,showTarget:!1,bodyScroll:!0,navRows:[{id:"boot",value:"inicio",onChange:()=>{},tabs:[{id:"inicio",label:"Inicio",icon:"mdi:home-outline"}]}]},n.createElement(p,{className:"isa-sw-boot-error",sx:{minHeight:"100%",display:"flex",alignItems:"center",justifyContent:"center",p:{xs:2,sm:3},boxSizing:"border-box"}},n.createElement(p,{sx:{width:"100%",maxWidth:680,textAlign:"center"}},n.createElement(m,{variant:"h6",component:"h1",sx:{fontWeight:700,mb:1.5}},l||`No se pudo iniciar ${c}`),n.createElement(u,{severity:"error",sx:{textAlign:"left",mb:2}},a),n.createElement(i,{variant:"outlined",onClick:()=>location.reload()},"Reintentar"))))),!0):!1}function g(a,{headline:l}={}){const e=document.getElementById("root");if(!e)return;if(!e.querySelector(".isa-app-boot")){e.innerHTML="";const t=document.createElement("div");t.className="isa-app-boot isa-app-boot--error",t.innerHTML=`<div class="isa-app-boot__mesh" aria-hidden="true"></div>
<div class="isa-app-boot__card" role="alert" aria-live="assertive">
  <div class="isa-app-boot__icon-wrap isa-app-boot__icon-wrap--error">
    <iconify-icon icon="mdi:alert-circle-outline" width="1.85em" height="1.85em"></iconify-icon>
  </div>
  <p class="isa-app-boot__title" id="isa-boot-title">${h()}</p>
  <p class="isa-app-boot__headline" id="isa-boot-headline"></p>
  <p class="isa-app-boot__error" id="isa-boot-error"></p>
  <div class="isa-app-boot__actions" id="isa-boot-actions">
    <button type="button" class="isa-app-boot__retry" onclick="location.reload()">Reintentar</button>
  </div>
</div>
<img class="isa-app-boot-watermark" src="https://pub-1c290cc606c8478899f5764899278571.r2.dev/brand/logo-insoft.png" alt="" aria-hidden="true" decoding="async" />`,e.appendChild(t)}const r=e.querySelector(".isa-app-boot");r?.classList.add("isa-app-boot--error");const s=r?.querySelector(".isa-app-boot__card");s?.setAttribute("role","alert"),s?.setAttribute("aria-live","assertive"),s?.setAttribute("aria-busy","false");const d=document.getElementById("isa-boot-icon");d&&d.setAttribute("icon","mdi:alert-circle-outline"),r?.querySelector(".isa-app-boot__icon-wrap")?.classList.add("isa-app-boot__icon-wrap--error");const p=r?.querySelector(".isa-app-boot__bar");p&&(p.hidden=!0);const m=h(),u=document.getElementById("isa-boot-title");u&&(u.textContent=m);let i=document.getElementById("isa-boot-headline");const c=document.getElementById("isa-boot-label");!i&&c&&(c.id="isa-boot-headline",c.className="isa-app-boot__headline",i=c),i&&(i.textContent=l||`No se pudo iniciar ${m}`);let o=document.getElementById("isa-boot-error");if(!o&&i&&(o=document.createElement("p"),o.id="isa-boot-error",o.className="isa-app-boot__error",i.after(o)),o&&(o.textContent=a),!document.getElementById("isa-boot-actions")){const t=document.createElement("div");t.id="isa-boot-actions",t.className="isa-app-boot__actions";const b=document.createElement("button");b.type="button",b.className="isa-app-boot__retry",b.textContent="Reintentar",b.addEventListener("click",()=>location.reload()),t.appendChild(b),(o||i||s)?.after(t)}}function y(a,l={}){const e=a instanceof Error?a.message:String(a);console.error(a),!_(e,l)&&g(e,l)}export{y as showBootError};
